### ISSUE TITLE
> cursed? are you sure were talking about the same essentials mod?

### ISSUE THREAD

**Issue by Capuchino12** [kerudion/chunksfadein#64]
> cursed? are you sure were talking about the same essentials mod?

If you mean that shitty mod "to play with friends" stuffed with payed cosmetics (even worse than in Bedrock Marketplace), incompatibilities with mods, forced updates, four (!!!) preloaders, invasiveness and other dirty things, then yeah, we are talking about the same mod from essential.gg.

> also it works just fine unless you turn "animation enabled" on in the chunks fadein setting

I'm not the CFI dev, but I understand that you can't easily fix compatibility with closed-source mod. You can't know exactly what kind of crap Essential is doing under the hood, and trying to fix it is like trying to walk with your eyes closed.
Anyways, you should wait for the answer from kerudion, I'm just warning you that you shouldn't expect much from Essential compatibility. It will be easier for you to use its open source alternatives for now. World Host or Cosmetica, for example, or any other mod with the same functionality.

By the way, if you want to play with your friends from Bedrock, this is what World Host will let you do in the future.

_Originally posted by @Felix14-v2 in https://github.com/kerudion/chunksfadein/issues/60#issuecomment-1834517494_
         

Bruhhhh, essential is a very clean mod, you know any other mod that let you play with friends? essential is free, unlike paying 5 dollars every month. you are just mad because it has cosmetics, a feature that is not that bad

**Comment by Felix14-v2** [comment]
> essential is a very clean mod

You are literally ignoring all the info I wrote before. Have you ever read it btw?


> you know any other mod that let you play with friends?

Moreover, I named you the mod for the same functionality – WorldHost. And WH isn't the only option – there are a bunch of similar mods:
- [P2P](https://modrinth.com/mod/p2p)
- [e4mc](https://modrinth.com/mod/e4mc)
- [mcwifipnp](https://modrinth.com/mod/mcwifipnp)
- [Ngrok LAN](https://modrinth.com/mod/ngrok-lan)
- [LAN Extender](https://modrinth.com/mod/lan-extender)
- [UPNP for dedicated servers](https://modrinth.com/mod/dedicatedmcupnp)
- [Global Host](https://modrinth.com/mod/globalhost)
- [WAN Party](https://modrinth.com/mod/wan-party)
- [OpenToPublic](https://modrinth.com/mod/opentopublic)
- etc

... as well as version independent 3rd party software like Ngrok itself, Playit.gg or Tunngle. Playing with friends via Essential is the worst argument in its defense, because you voluntarily limit yourself to the bandwidth of the Essential network (other mods are able to use UPnP to achieve maximum speed), independence from Essential (all listed mods except one do not require installation for other players), and compatibility with other mods.

> you are just mad because it has cosmetics, a feature that is not that bad

... but it is. You can't give a single argument in its defense. For example: let's imagine that I don't want to see any cosmetics because my PC is too weak to load it with additional graphics. Using other mods I can make a decision wether to install additional cosmetic mods or not. Using Essential I'm forced to use its cosmetics. What's your argument?
