### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by RaptaG** [kerudion/chunksfadein#8]
The current name doesn't fully describe this mod + it reminds of other mods.

Suggestion: Enhanced Chunks

**Comment by kerudion** [comment]
Hello!
I think, that everything that has "chunks" with "enhanced" "animation" (or something like that) will remind similar mods. As you said, mod name must fully describe mod, and because all these mods are doing almost the same thing, their names will be similar due to their similar functions.
Also, you can easily say "Chunks are fading in" for both animation and color transitions, so it's not so bad. And renaming mod is very painful, can confuse players and lead to unexpected errors.
